name: myseries

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install axios cheerio fs-extra

      - name: Run script
        run: node my.js

      - name: Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "update data" || echo "no commit"
          git push
